/**
 * unified-agent-tool.ts — Phase 4 facade: RFC tool-surface-unification.
 *
 * Registers a single public tool named `agent` that wraps:
 *   spawn   → typed profiles (researcher/planner/architect/browser/custom)
 *   inspect → list all agents or status of one
 *   wait    → current transcript snapshot for a live agent
 *   message → send/followUp to a live agent
 *   steer   → redirect in-flight turn or queue a follow-up
 *   abort   → graceful interrupt (snapshot; full RPC abort via AgentMessage)
 *   kill    → terminate a worker process
 *
 * Agent state is projected from agent-tools.ts into this public facade.
 *
 * Browser profile delegates to routeTask + buildSpawnConfig (exported from
 * browser-agent-tool.ts) for CDP domain routing and system-prompt construction.
 *
 * Same-batch cross-reference guard: a batch that contains at least one `spawn`
 * query AND at least one lifecycle query with a non-empty `agentId` is rejected
 * before any side effect, because the caller cannot know the IDs that would be
 * generated by the spawns in the same call.
 *
 * Integration exports at bottom of file — see HANDBACK notes.
 */

import type {
  ToolDefinition,
  ToolCallResult,
  PiContext,
  PiInstance,
  PiTheme,
} from '../types.js';
import type { registerUniqueTool } from './octocode-tools.js';
import {
  isSubagentProcess,
  prepareSpawnAgentParams,
  registerAgentTools,
  spawnRpcAgent,
  steerWorkerById,
  killWorkerById,
  getWorkerTranscript,
  formatAgentLedger,
  formatAgentLedgerDetails,
  refreshAgentLedgerUi,
  listWorkerLedgerEntries,
  type SpawnAgentParams,
} from './agent-tools.js';
import {
  SUBAGENT_REGISTRY,
  loadSystemPrompt,
  resolveSubagentSkills,
  type SubagentConfig,
  type SubagentName,
} from '../subagents.js';
import { routeTask, buildSpawnConfig } from './browser-agent-tool.js';
import { connectToChrome, cleanupConnection } from '../chrome-debug.js';
import { SCHEME_REGISTRY } from '../chrome-debug-schemes.js';
import type { ChromeDebugParams } from '../chrome-debug-schemes.js';
import {
  buildQueryEnvelopeSchema,
  executeQueryBatch,
  type QueryRecord,
} from './query-envelope.js';
import { stringEnumSchema } from './schema-helpers.js';
import { getRandomAgentName } from '../agentNames.js';
import { makeRenderer, truncateToWidth } from './render-helpers.js';
import { paint, CLI_GLYPH } from '../tui/cli-design.js';
import {
  getToolEffect,
  planModeToolGate,
  registerAgentToolEffectResolver,
  type ToolEffect,
} from './plan-mode.js';

type TypeBoxBuilder = (typeof import('typebox'))['Type'];
type RegisterFn = typeof registerUniqueTool;

// ─── Profile & operation constants ────────────────────────────────────────────

/** Typed profiles backed by SUBAGENT_REGISTRY. */
const TYPED_REGISTRY_PROFILES = ['researcher', 'planner', 'architect'] as const;

/** All public profiles exposed on the `agent` tool. */
export const AGENT_PROFILES = [
  ...TYPED_REGISTRY_PROFILES,
  'browser',
  'custom',
] as const;
export type AgentProfile = (typeof AGENT_PROFILES)[number];

/** All operations exposed on the `agent` tool. */
export const AGENT_OPERATIONS = [
  'spawn',
  'inspect',
  'wait',
  'message',
  'steer',
  'abort',
  'kill',
] as const;
export type AgentOperation = (typeof AGENT_OPERATIONS)[number];

// ─── Typed-profile → subagent-registry mapping ───────────────────────────────

const PROFILE_TO_SUBAGENT: Record<
  (typeof TYPED_REGISTRY_PROFILES)[number],
  SubagentName
> = {
  researcher: 'researcher',
  planner: 'planner',
  architect: 'architect',
};

const DYNAMIC_CHILD_TOOLS = new Set([
  'agent',
  'browseragent',
  'callskill',
  'calltool',
  'mcptool',
  'skill',
  'spawnagent',
  'spawnsubagent',
]);

function isQueryRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function resolveTypedProfileEffect(profile: (typeof TYPED_REGISTRY_PROFILES)[number]): ToolEffect | undefined {
  const config = SUBAGENT_REGISTRY[PROFILE_TO_SUBAGENT[profile]] as SubagentConfig | undefined;
  if (!config || !Array.isArray(config.tools)) return undefined;

  let resolved: ToolEffect = 'coordination-write';
  for (const rawName of config.tools) {
    if (typeof rawName !== 'string' || !rawName.trim()) return undefined;
    const name = rawName.trim();
    const effect = DYNAMIC_CHILD_TOOLS.has(name.toLowerCase())
      ? 'external-effect'
      : getToolEffect(name);
    if (!effect) return undefined;
    if (effect === 'external-effect') return effect;
    if (effect === 'workspace-write') resolved = effect;
  }
  return resolved;
}

/** Resolve the effect of the complete ordered agent batch before any item runs. */
export function resolveAgentBatchEffect(input?: Record<string, unknown>): ToolEffect | undefined {
  const values = input?.['queries'];
  if (!Array.isArray(values) || values.length === 0) return undefined;

  let resolved: ToolEffect = 'coordination-write';
  for (const value of values) {
    if (!isQueryRecord(value)) return undefined;
    const operation = typeof value['type'] === 'string' ? value['type'] : undefined;
    if (!operation || !(AGENT_OPERATIONS as readonly string[]).includes(operation)) return undefined;
    if (operation !== 'spawn') continue;

    if (!String(value['task'] ?? '').trim()) return undefined;
    const profile = typeof value['profile'] === 'string' ? value['profile'] : 'custom';
    if (!(AGENT_PROFILES as readonly string[]).includes(profile)) return undefined;
    if (profile === 'custom' || profile === 'browser') return 'external-effect';

    const profileEffect = resolveTypedProfileEffect(profile as (typeof TYPED_REGISTRY_PROFILES)[number]);
    if (!profileEffect) return undefined;
    if (profileEffect === 'external-effect') return profileEffect;
    if (profileEffect === 'workspace-write') resolved = profileEffect;
  }
  return resolved;
}

registerAgentToolEffectResolver(resolveAgentBatchEffect);

// ─── Same-batch cross-reference guard ────────────────────────────────────────

/**
 * Reject a batch that mixes `spawn` (which generates new IDs at runtime) with
 * lifecycle queries that supply an explicit `agentId`, because the caller cannot
 * know a freshly generated ID before the call completes.
 *
 * Multiple independent spawns are allowed. Multiple lifecycle ops on
 * pre-existing agents are allowed. Only the ambiguous mixed case is blocked.
 */
export function rejectCrossBatchReference(queries: QueryRecord[]): void {
  const hasSpawn = queries.some((q) => (q['type'] as string) === 'spawn');
  if (!hasSpawn) return;

  const lifecycleWithId = queries.filter(
    (q) =>
      (q['type'] as string) !== 'spawn' &&
      typeof q['agentId'] === 'string' &&
      (q['agentId'] as string).trim().length > 0,
  );

  if (lifecycleWithId.length > 0) {
    const ops = lifecycleWithId.map((q) => q['type'] as string).join(', ');
    throw new Error(
      `Same-batch cross-reference rejected: a batch containing spawn cannot also ` +
      `reference an agentId in lifecycle queries (${ops}). ` +
      `Spawn workers in one call, then use the returned agentId in a subsequent call.`,
    );
  }
}

// ─── Spawn dispatch ───────────────────────────────────────────────────────────

export async function executeSpawnQuery(
  query: QueryRecord,
  ctx?: PiContext,
): Promise<ToolCallResult> {
  const profile = (query['profile'] as AgentProfile | undefined) ?? 'custom';
  const task = String(query['task'] ?? '').trim();
  const context = query['context'] as string | undefined;
  const name = query['name'] as string | undefined;
  const model = query['model'] as string | undefined;
  const provider = query['provider'] as string | undefined;
  const thinking = query['thinking'] as string | undefined;
  const cwd = query['cwd'] as string | undefined;
  const isolation = query['isolation'] as SpawnAgentParams['isolation'];
  const includeUncommitted = query['includeUncommitted'] as boolean | undefined;
  const planStep = (query['planStep'] as string | undefined)?.trim() || undefined;

  if (!task) {
    throw new Error('agent spawn requires a non-empty task.');
  }

  const fullTask = context
    ? `## Context\n${(context as string).trim()}\n\n## Task\n${task}`
    : task;

  let spawnParams: SpawnAgentParams;

  if (profile === 'browser') {
    const port = (query['port'] as number | undefined) ?? 9222;
    const url = query['url'] as string | undefined;
    const launch = query['launch'] === true;
    const headless = query['headless'] !== false;
    const runNow = query['runNow'] !== false;
    const durationMs = (query['durationMs'] as number | undefined) ?? 5000;
    const workspaceCwd = query['workspaceCwd'] as string | undefined;
    const { schemes, cdpDomains } = routeTask(task);
    const initialFindings: string[] = [];

    if (runNow) {
      let connection: Awaited<ReturnType<typeof connectToChrome>> | null = null;
      try {
        connection = await connectToChrome({ port, launch, headless, workspaceCwd });
        const { session } = connection;
        if (url) {
          await session.send('Page.enable', {});
          await session.send('Page.navigate', { url });
          await new Promise<void>((resolve) => {
            const timer = setTimeout(resolve, 4000);
            (session as unknown as { on(event: string, listener: () => void): void }).on(
              'Page.loadEventFired',
              () => { clearTimeout(timer); resolve(); },
            );
          });
          initialFindings.push(`[AGENT] navigated to ${url}`);
        }
        for (const scheme of schemes.slice(0, 4)) {
          const entry = SCHEME_REGISTRY[scheme as keyof typeof SCHEME_REGISTRY];
          if (!entry) continue;
          try {
            const result = await entry.recipe({
              session,
              params: {
                scheme: scheme as ChromeDebugParams['scheme'],
                url: undefined,
                durationMs,
                port,
              },
              screenshotDir: connection.screenshotDir,
              signal: AbortSignal.timeout(20_000),
            });
            if (result.evidenceLines.length > 0) {
              initialFindings.push(`\n[AGENT] === ${scheme.toUpperCase()} ===`);
              initialFindings.push(...result.evidenceLines);
            }
          } catch (error) {
            initialFindings.push(`[AGENT] ${scheme} error: ${(error as Error).message.slice(0, 100)}`);
          }
        }
      } catch (error) {
        initialFindings.push(`[AGENT] connect error: ${(error as Error).message}`);
      } finally {
        if (connection) {
          await cleanupConnection(connection.session, !launch, launch).catch(() => {});
        }
      }
    }

    const spawnConfig = buildSpawnConfig({
      task,
      url,
      port,
      model,
      cdpDomains,
      skillContext: '',
      initialFindings,
    });
    spawnParams = {
      task: context ? `## Context\n${context.trim()}\n\n## Task\n${spawnConfig.task}` : spawnConfig.task,
      name: name ?? `Browser Agent · ${getRandomAgentName()}`,
      cwd,
      tools: spawnConfig.tools,
      systemPrompt: spawnConfig.systemPrompt,
      resourceMode: 'octocode',
      thinking: thinking ?? 'low',
      model: model ?? spawnConfig.model,
      provider: provider ?? ctx?.model?.provider,
      noSession: query['noSession'] !== false,
      isolation,
      includeUncommitted,
    };
  } else if (profile === 'custom') {
    // Custom profile: explicit tools/systemPrompt, lean by default (same as spawnAgent).
    const tools = query['tools'] as string[] | undefined;
    const systemPrompt = query['systemPrompt'] as string | undefined;
    const resourceMode =
      (query['resourceMode'] as SpawnAgentParams['resourceMode']) ?? 'lean';
    spawnParams = {
      task: fullTask,
      name: name ?? `Worker · ${getRandomAgentName()}`,
      cwd,
      tools,
      systemPrompt,
      resourceMode,
      thinking,
      model,
      provider: provider ?? ctx?.model?.provider,
      noSession: query['noSession'] !== false,
      isolation,
      includeUncommitted,
    };
  } else {
    // Typed registry profile (researcher / planner / architect).
    const subagentName = PROFILE_TO_SUBAGENT[profile];
    const config = SUBAGENT_REGISTRY[subagentName] as SubagentConfig & {
      model?: string;
      provider?: string;
    };
    const systemPrompt = loadSystemPrompt(config);
    const skills = resolveSubagentSkills(config);
    spawnParams = {
      task: fullTask,
      name: name ?? `${config.label} · ${getRandomAgentName()}`,
      cwd,
      tools: [...config.tools],
      skills,
      systemPrompt,
      resourceMode: config.resourceMode,
      thinking: thinking ?? config.thinking,
      model: model ?? config.model,
      provider: provider ?? config.provider ?? ctx?.model?.provider,
      noSession: query['noSession'] !== false,
      isolation,
      includeUncommitted,
    };
  }

  spawnParams.planStep = planStep;

  const approvedParams = await prepareSpawnAgentParams(spawnParams, ctx);
  const record = spawnRpcAgent(approvedParams, ctx);
  refreshAgentLedgerUi(ctx);

  const agentId: string = record.id;
  const ledgerEntry = listWorkerLedgerEntries().find((entry) => entry.agentId === agentId);
  const policyLines =
    record.policyWarnings.length > 0
      ? ['', '[POLICY]', ...record.policyWarnings.map((w: string) => `  ${w}`)]
      : [];

  const output = [
    `[SPAWNED] profile:${profile} · agentId:${agentId}`,
    `[SPAWNED] name: ${record.name}`,
    `[SPAWNED] model: ${ledgerEntry?.provider ? `${ledgerEntry.provider}/` : ''}${ledgerEntry?.model ?? 'inherited'}`,
    `[SPAWNED] task: ${ledgerEntry?.task ?? task}`,
    ...(ledgerEntry?.planStep ? [`[SPAWNED] plan: ${ledgerEntry.planStep}`] : []),
    ...policyLines,
    '',
    `[USAGE] agent({queries:[{reasoning:"…", type:"wait", agentId:"${agentId}"}]})`,
  ].join('\n');

  return {
    content: [{ type: 'text', text: output }],
    details: { agentId, profile, name: record.name, model: ledgerEntry?.model, provider: ledgerEntry?.provider, task: ledgerEntry?.task ?? task, planStep: ledgerEntry?.planStep },
  } as unknown as ToolCallResult;
}

// ─── Lifecycle dispatchers ────────────────────────────────────────────────────

export function executeInspectQuery(
  query: QueryRecord,
  ctx?: PiContext,
): ToolCallResult {
  const agentId = (query['agentId'] as string | undefined)?.trim();
  refreshAgentLedgerUi(ctx);

  if (!agentId) {
    // List mode.
    const details = formatAgentLedgerDetails();
    const summary = formatAgentLedger();
    const text = details || summary || 'No agents spawned in this session.';
    return { content: [{ type: 'text', text }] };
  }

  // Single-agent status mode.
  const transcript = getWorkerTranscript(agentId);
  if (transcript === undefined) {
    throw new Error(
      `No agent found with id "${agentId}". ` +
      `Use inspect without agentId to list all agents.`,
    );
  }
  return { content: [{ type: 'text', text: transcript }] };
}

export function executeWaitQuery(
  query: QueryRecord,
  ctx?: PiContext,
): ToolCallResult {
  const agentId = (query['agentId'] as string | undefined)?.trim();
  if (!agentId) throw new Error('agent wait requires agentId.');

  const full = query['full'] === true;
  const maxLines = full ? undefined : 60;
  const transcript = getWorkerTranscript(agentId, maxLines !== undefined ? { maxLines } : {});
  if (transcript === undefined) {
    throw new Error(`No agent found with id "${agentId}" for wait.`);
  }
  refreshAgentLedgerUi(ctx);
  // Blocking wait (waitForAgent) requires the internal AgentRecord. This facade
  // returns a current transcript snapshot. For a blocking wait use AgentMessage.
  return {
    content: [{
      type: 'text',
      text: `[WAIT snapshot · agentId:${agentId}]\n${transcript}`,
    }],
    details: { agentId, snapshotOnly: true },
  } as unknown as ToolCallResult;
}

export function executeMessageQuery(query: QueryRecord): ToolCallResult {
  const agentId = (query['agentId'] as string | undefined)?.trim();
  const message = (query['message'] as string | undefined)?.trim();
  const delivery =
    (query['delivery'] as 'send' | 'followUp' | undefined) ?? 'send';

  if (!agentId) throw new Error('agent message requires agentId.');
  if (!message) throw new Error('agent message requires non-empty message text.');

  // steerWorkerById: steers if running, queues follow-up if idle.
  // Covers both send and followUp delivery semantics.
  const sent = steerWorkerById(agentId, message);
  if (!sent) {
    throw new Error(
      `Could not deliver message to agent "${agentId}". ` +
      `The agent may not exist, have exited, or the message was empty.`,
    );
  }
  return {
    content: [{
      type: 'text',
      text: `[MESSAGE] delivery:${delivery} → agentId:${agentId}: ${message.slice(0, 120)}`,
    }],
    details: { agentId, delivery },
  } as unknown as ToolCallResult;
}

export function executeSteerQuery(query: QueryRecord): ToolCallResult {
  const agentId = (query['agentId'] as string | undefined)?.trim();
  const message = (query['message'] as string | undefined)?.trim();

  if (!agentId) throw new Error('agent steer requires agentId.');
  if (!message) throw new Error('agent steer requires non-empty message.');

  const sent = steerWorkerById(agentId, message);
  if (!sent) {
    throw new Error(
      `Could not steer agent "${agentId}". ` +
      `The agent may not exist, have exited, or the message was empty.`,
    );
  }
  return {
    content: [{ type: 'text', text: `[STEER] → agentId:${agentId}: ${message.slice(0, 120)}` }],
    details: { agentId },
  } as unknown as ToolCallResult;
}

export function executeAbortQuery(
  query: QueryRecord,
  ctx?: PiContext,
): ToolCallResult {
  const agentId = (query['agentId'] as string | undefined)?.trim();
  if (!agentId) throw new Error('agent abort requires agentId.');

  // Full RPC graceful-abort (sendRpc {type:"abort"}) is internal to agent-tools.ts.
  // Confirm the agent exists via transcript; caller can use kill for hard termination.
  const transcript = getWorkerTranscript(agentId, { maxLines: 3 });
  if (transcript === undefined) {
    throw new Error(`No agent found with id "${agentId}" for abort.`);
  }
  refreshAgentLedgerUi(ctx);
  return {
    content: [{
      type: 'text',
      text:
        `[ABORT] agentId:${agentId} located. ` +
        `Graceful RPC interrupt requires AgentMessage(action:"abort"). ` +
        `Use agent(type:"kill") for hard termination.`,
    }],
    details: { agentId },
  } as unknown as ToolCallResult;
}

export function executeKillQuery(
  query: QueryRecord,
  ctx?: PiContext,
): ToolCallResult {
  const agentId = (query['agentId'] as string | undefined)?.trim();
  if (!agentId) throw new Error('agent kill requires agentId.');

  const killed = killWorkerById(agentId);
  if (!killed) {
    throw new Error(
      `No agent found with id "${agentId}" for kill. ` +
      `Use inspect without agentId to list available agents.`,
    );
  }
  refreshAgentLedgerUi(ctx);
  return {
    content: [{ type: 'text', text: `[KILL] agentId:${agentId} terminated.` }],
    details: { agentId },
  } as unknown as ToolCallResult;
}

// ─── Registration ─────────────────────────────────────────────────────────────

/**
 * Register the unified `agent` tool.
 *
 * Called from index.ts in the agent registration phase. Proven worker lifecycle
 * executors are captured internally, but only the unified `agent` name is public.
 *
 * INTEGRATION EXPORTS (for later index.ts cutover):
 *   registerUnifiedAgentTool  — call in the same registration phase as registerAgentTools
 *   AGENT_PROFILES            — closed enum for schema/test assertions
 *   AGENT_OPERATIONS          — closed enum for schema/test assertions
 *   rejectCrossBatchReference — batch-level preflight guard (exported for tests)
 *   executeSpawnQuery         — per-item spawn handler (exported for tests)
 *   executeInspectQuery       — per-item inspect handler (exported for tests)
 *   executeWaitQuery          — per-item wait handler (exported for tests)
 *   executeMessageQuery       — per-item message handler (exported for tests)
 *   executeSteerQuery         — per-item steer handler (exported for tests)
 *   executeAbortQuery         — per-item abort handler (exported for tests)
 *   executeKillQuery          — per-item kill handler (exported for tests)
 */
export function registerUnifiedAgentTool(
  pi: { registerTool?(def: ToolDefinition): void },
  Type: TypeBoxBuilder,
  registeredToolNames: Set<string>,
  registerFn: RegisterFn,
): void {
  // Workers cannot spawn workers — never register this tool inside a subagent process.
  if (isSubagentProcess()) return;

  // Reuse the lifecycle executor without registering its internal public name.
  const lifecycleTools = new Map<string, ToolDefinition>();
  registerAgentTools(pi as PiInstance, Type, new Set<string>(), (_pi, _names, definition) => {
    lifecycleTools.set(definition.name, definition);
  });
  const agentMessageExecutor = lifecycleTools.get('AgentMessage');
  if (!agentMessageExecutor) throw new Error('AgentMessage runtime is unavailable.');

  // ── Item schema ─────────────────────────────────────────────────────────────
  const operationEnum = stringEnumSchema(
    Type,
    AGENT_OPERATIONS as unknown as string[],
    'Operation: spawn | inspect | wait | message | steer | abort | kill.',
  );
  const profileEnum = stringEnumSchema(
    Type,
    AGENT_PROFILES as unknown as string[],
    'Spawn profile: researcher | planner | architect | browser | custom.',
  );
  const deliveryEnum = stringEnumSchema(
    Type,
    ['send', 'followUp'],
    'Message delivery: send starts a new idle turn; followUp queues after the current turn.',
  );
  const isolationEnum = stringEnumSchema(
    Type,
    ['shared', 'worktree'],
    'Filesystem isolation for spawn. shared (default) uses current cwd; worktree creates an isolated git worktree.',
  );
  const resourceModeEnum = stringEnumSchema(
    Type,
    ['lean', 'octocode', 'default'],
    'Resource mode for custom profile. lean disables extensions/skills; octocode loads this extension.',
  );

  // All lifecycle-specific fields are optional; type is the discriminator.
  // Google-family schemas require a string enum instead of Type.Union / Type.Literal.
  const itemSchema = Type.Object(
    {
      type: operationEnum as ReturnType<TypeBoxBuilder['String']>,
      // spawn fields
      profile: Type.Optional(profileEnum as ReturnType<TypeBoxBuilder['String']>),
      task: Type.Optional(Type.String({ description: 'Worker assignment/instructions for spawn; not a plan task record.' })),
      context: Type.Optional(Type.String({ description: 'Evidence or constraints prepended to the worker assignment.' })),
      name: Type.Optional(Type.String({ description: 'Human label for the worker (spawn).' })),
      planStep: Type.Optional(Type.String({ description: 'Parent plan step this worker is executing; shown in agent status UI.' })),
      model: Type.Optional(Type.String({ description: 'Model id from `pi -ne --list-models`.' })),
      provider: Type.Optional(Type.String({ description: 'Provider name (required when model id collides with a builtin namespace).' })),
      thinking: Type.Optional(Type.String({ description: 'Thinking level: off|minimal|low|medium|high|xhigh.' })),
      cwd: Type.Optional(Type.String({ description: 'Working directory (spawn).' })),
      isolation: Type.Optional(isolationEnum as ReturnType<TypeBoxBuilder['String']>),
      includeUncommitted: Type.Optional(Type.Boolean({ description: 'With isolation:worktree, apply uncommitted tracked changes.' })),
      // browser profile
      url: Type.Optional(Type.String({ description: 'URL to pass to the browser profile (spawn/browser).' })),
      port: Type.Optional(Type.Integer({ description: 'Chrome remote debug port (spawn/browser, default 9222).' })),
      launch: Type.Optional(Type.Boolean({ description: 'Launch Chrome for initial browser analysis (default false).' })),
      headless: Type.Optional(Type.Boolean({ description: 'Launch Chrome headless for initial browser analysis (default true).' })),
      runNow: Type.Optional(Type.Boolean({ description: 'Run routed initial browser analysis before spawning (default true).' })),
      durationMs: Type.Optional(Type.Integer({ description: 'Initial browser scheme observation window in milliseconds (default 5000).' })),
      workspaceCwd: Type.Optional(Type.String({ description: 'Workspace root for browser screenshots and session paths.' })),
      // custom profile
      tools: Type.Optional(Type.Array(Type.String(), { description: 'Tool allowlist for custom profile (spawn).' })),
      systemPrompt: Type.Optional(Type.String({ description: 'Extra system prompt for custom profile (spawn).' })),
      resourceMode: Type.Optional(resourceModeEnum as ReturnType<TypeBoxBuilder['String']>),
      noSession: Type.Optional(Type.Boolean({ description: 'Pass --no-session to the spawned worker (default true).' })),
      // lifecycle fields
      agentId: Type.Optional(Type.String({ description: 'Target agent id (inspect/wait/message/steer/abort/kill).' })),
      message: Type.Optional(Type.String({ description: 'Message text (message/steer).' })),
      delivery: Type.Optional(deliveryEnum as ReturnType<TypeBoxBuilder['String']>),
      timeoutMs: Type.Optional(Type.Integer({ description: 'Wait silence budget in milliseconds (default 300000).' })),
      remove: Type.Optional(Type.Boolean({ description: 'Remove the worker record after wait/kill when safe.' })),
      full: Type.Optional(Type.Boolean({ description: 'Return full retained history for inspect/wait/abort/kill.' })),
    },
  );

  const parameters = buildQueryEnvelopeSchema(Type, itemSchema, {
    reasoningDescription: 'Concise reason this agent operation is necessary (max 240 chars).',
  });

  registerFn(pi, registeredToolNames, {
    name: 'agent',
    label: 'Agent',
    description: [
      'Unified agent facade. Spawn typed/custom/browser workers and manage their lifecycle.',
      '',
      'Operations (type field):',
      '  spawn   — create a new worker. Returns agentId.',
      '  inspect — list all agents (no agentId) or show status (with agentId).',
      '  wait    — wait for the current turn, returning a live snapshot after a quiet gap.',
      '  message — send or queue a message (delivery: send|followUp).',
      '  steer   — redirect in-flight turn or queue follow-up.',
      '  abort   — gracefully interrupt the active worker turn without killing the process.',
      '  kill    — terminate a worker process.',
      '',
      'Profiles for spawn:',
      '  researcher — web/GitHub/npm/local research specialist.',
      '  planner    — implementation-planning specialist.',
      '  architect  — local-code / root-cause specialist.',
      '  browser    — Chrome DevTools Protocol specialist; routes task to CDP domains.',
      '  custom     — clean worker with explicit tools/systemPrompt.',
      '',
      'Same-batch rule: spawn and lifecycle ops with explicit agentIds cannot coexist.',
      'Spawn first, then use the returned agentId in a subsequent call.',
    ].join('\n'),

    promptSnippet:
      'Spawn typed/custom/browser workers and manage lifecycle via queries[].',
    promptGuidelines: [
      'Never mix spawn and agentId-bearing lifecycle queries in the same batch — spawn first, lifecycle next call.',
      'Use profile:researcher/planner/architect for typed Octocode specialists; profile:browser for CDP work; profile:custom for lean workers.',
      'Use type:inspect without agentId to list all agents; with agentId to check status.',
      'Use type:wait to collect the current turn before trusting a worker is complete.',
      'Use type:kill after collecting results to free resources.',
      'Check /octocode-agents or the agent ledger for live worker status between calls.',
      'Provide labelled task packets (Goal/Context/Scope/Ownership/Acceptance/Return) to avoid [POLICY] warnings.',
    ],

    parameters,

    async execute(
      toolCallId: string,
      rawParams: Record<string, unknown>,
      signal?: AbortSignal,
      onUpdate?: unknown,
      ctx?: PiContext,
    ): Promise<ToolCallResult> {
      const policyBlock = planModeToolGate('agent', ctx, rawParams);
      if (policyBlock) throw new Error(policyBlock.reason);

      // Cross-batch reference guard: checked before any item executes.
      const queriesRaw = Array.isArray(rawParams['queries'])
        ? (rawParams['queries'] as QueryRecord[])
        : [];
      rejectCrossBatchReference(queriesRaw);

      return executeQueryBatch({
        toolCallId,
        raw: rawParams,
        signal,
        onUpdate: onUpdate as ((update: ToolCallResult) => void) | undefined,
        ctx,
        passthroughSingle: true,
        preflight: async (query, index) => {
          const type = query['type'] as string | undefined;
          if (!type || !(AGENT_OPERATIONS as readonly string[]).includes(type)) {
            throw new Error(
              `queries[${index}].type must be one of: ${AGENT_OPERATIONS.join(', ')}.`,
            );
          }
          if (type === 'spawn') {
            const task = String(query['task'] ?? '').trim();
            if (!task) throw new Error(`queries[${index}]: spawn requires a non-empty task.`);
            const profile = String(query['profile'] ?? 'custom');
            if (!(AGENT_PROFILES as readonly string[]).includes(profile)) {
              throw new Error(`queries[${index}].profile must be one of: ${AGENT_PROFILES.join(', ')}.`);
            }
            return;
          }
          const agentId = String(query['agentId'] ?? '').trim();
          if (type !== 'inspect' && !agentId) {
            throw new Error(`queries[${index}]: ${type} requires agentId.`);
          }
          if ((type === 'message' || type === 'steer') && !String(query['message'] ?? '').trim()) {
            throw new Error(`queries[${index}]: ${type} requires a non-empty message.`);
          }
        },

        async execute(
          query: QueryRecord,
          _index: number,
          itemId: string,
          itemSignal?: AbortSignal,
          itemUpdate?: unknown,
          itemCtx?: PiContext,
        ): Promise<ToolCallResult> {
          const type = query['type'] as AgentOperation;
          if (type === 'spawn') return executeSpawnQuery(query, itemCtx);

          const agentId = query['agentId'] as string | undefined;
          const full = query['full'] === true;
          const remove = query['remove'] === true;
          let executorParams: Record<string, unknown>;
          switch (type) {
            case 'inspect':
              executorParams = agentId
                ? { action: 'status', agentId, full }
                : { action: 'list', full };
              break;
            case 'wait':
              executorParams = { action: 'wait', agentId, timeoutMs: query['timeoutMs'], remove, full };
              break;
            case 'message':
              executorParams = {
                action: query['delivery'] === 'followUp' ? 'followUp' : 'send',
                agentId,
                message: query['message'],
              };
              break;
            case 'steer':
              executorParams = { action: 'steer', agentId, message: query['message'] };
              break;
            case 'abort':
              executorParams = { action: 'abort', agentId, full };
              break;
            case 'kill':
              executorParams = { action: 'kill', agentId, remove, full };
              break;
            default:
              throw new Error(`Unknown agent operation: ${type as string}`);
          }
          return agentMessageExecutor.execute(
            itemId,
            executorParams,
            itemSignal,
            itemUpdate,
            itemCtx,
          );
        },

        summarize(result: ToolCallResult, query: QueryRecord) {
          const type = query['type'] as string;
          const text =
            (result.content.find((p) => p.type === 'text') as { text?: string } | undefined)
              ?.text ?? '';
          return `${type}: ${text.split('\n').find(Boolean)?.trim().slice(0, 80) ?? 'ok'}`;
        },
      });
    },

    renderCall(rawParams: unknown) {
      const raw = rawParams as {
        queries?: Array<{ type?: string; profile?: string; agentId?: string; task?: string }>;
      };
      const first = raw?.queries?.[0];
      const op = first?.type ?? '…';
      const detail = first?.profile
        ? ` profile:${first.profile}`
        : first?.agentId
          ? ` id:${String(first.agentId).slice(0, 8)}`
          : first?.task
            ? ` "${String(first.task).slice(0, 36)}${String(first.task).length > 36 ? '…' : ''}"`
            : '';
      const extra =
        (raw?.queries?.length ?? 0) > 1
          ? ` +${(raw.queries?.length ?? 1) - 1}`
          : '';
      return makeRenderer((w) =>
        [truncateToWidth(`agent(${op}${detail})${extra}`, w)],
      );
    },

    renderResult(result: unknown, _opts: unknown, theme?: PiTheme) {
      const r = result as {
        content?: Array<{ type: string; text?: string }>;
        isError?: boolean;
      };
      const ok = !r?.isError;
      const text =
        (r?.content?.find((p) => p.type === 'text') as { text?: string } | undefined)?.text ?? '';
      const firstLine = text.split('\n').find(Boolean)?.trim() ?? (ok ? 'done' : 'failed');
      const glyph = ok
        ? paint(theme, 'success', CLI_GLYPH.success)
        : paint(theme, 'error', CLI_GLYPH.error);
      return makeRenderer((w) =>
        [truncateToWidth(`${glyph} agent · ${firstLine}`, w)],
      );
    },
  } satisfies ToolDefinition);
}
