import { describe, expect, it } from 'vitest';
import { ExecutionScope, HookCatalog, assemblePrompt, parseCodexHooks, parseRpcRequest, revision, type HookSourceDescriptor } from '../src/index.js';
describe('external boundaries', () => {
  it('validates Codex hooks and preserves unsupported definitions', () => { const parsed = parseCodexHooks({ hooks: { PreToolUse: [{ matcher: '^edit$', hooks: [{ type: 'command', command: './check', async: false }] }], FutureEvent: [{ value: 1 }] } }); expect(parsed.hooks.PreToolUse?.[0]?.handlers[0]).toMatchObject({ type: 'command', timeoutSeconds: 600 }); expect(parsed.unsupported).toHaveLength(1); expect(() => parseCodexHooks({ hooks: { SessionEnd: [{ hooks: [{ type: 'command', command: './end', timeout: 4 }] }] } })).toThrow(/timeout/i); });
  it('rejects unknown RPC major versions', () => { expect(() => parseRpcRequest({ protocolVersion: 2, requestId: 'r', command: { type: 'runtime.snapshot' } })).toThrow(/version/i); });
});
describe('hook discovery and trust', () => {
  it('merges eligible sources deterministically and invalidates changed hashes', () => { const catalog = new HookCatalog(); const source = (id: string, scope: HookSourceDescriptor['scope'], hash: string, order: number): HookSourceDescriptor => ({ id, scope, provenance: id, managed: false, rawHash: hash, normalizedHash: hash, trust: 'trusted', revision: revision(hash), discoveryOrder: order }); const config = parseCodexHooks({ hooks: { PreToolUse: [{ hooks: [{ type: 'command', command: './check' }] }] } }); catalog.register(source('workspace', 'workspace', 'h1', 1), config); catalog.review('workspace', 'h1'); expect(catalog.effective(false, false)).toHaveLength(0); expect(catalog.effective(true, false)).toHaveLength(1); catalog.register(source('workspace', 'workspace', 'h2', 1), config); expect(catalog.effective(true, false)).toHaveLength(0); expect(() => catalog.review('workspace', 'h1')).toThrow(/hash/i); });
});
describe('pure runtime primitives', () => {
  it('cascades cancellation to child scopes', () => { const parent = new ExecutionScope('turn'); const child = parent.child('tool'); parent.cancel('stop'); expect(child.signal.aborted).toBe(true); expect(child.signal.reason).toBe('stop'); });
  it('assembles prompts deterministically with semantic receipt', () => { const snapshot = assemblePrompt([{ id: 'b', placement: 'after-user', priority: 0, content: 'B', provenance: 'test', trusted: true }, { id: 'a', placement: 'system', priority: 0, content: 'A', provenance: 'test', trusted: true }]); expect(snapshot.text).toBe('A\n\nB'); expect(snapshot.semanticDigest).toMatch(/^[0-9a-f]{8}$/); });
});
