import { describe, expect, it } from 'vitest';
import { PolicyChain, RuntimeKernel, ToolRegistry, sessionId, type ModelPort, type ToolDefinition } from '../src/index.js';
const definition = (execute: () => Promise<unknown>, name = 'lookup'): ToolDefinition => ({ name, label: name, description: name, schemaVersion: 1, inputSchema: { type: 'object' }, outputSchema: { type: 'object' }, outputVersion: 1, policy: { effect: 'read', trust: 'none', approval: 'never', plan: 'allowed' }, execute: async () => ({ ok: true, content: await execute(), detailsVersion: 1 }) });
describe('bounded model/tool loop', () => {
  it('runs policy before one effect and feeds the result into the next request', async () => { let calls = 0; const requests: number[] = []; const model: ModelPort = { run: async (request, context) => { requests.push(request.messages.length); if (requests.length === 1) { expect(request.tools?.[0]?.name).toBe('lookup'); await context.emit?.({ type: 'tool-call', id: 'call-1', name: 'lookup', input: { q: 1 } }); return { stop: 'tool', usage: { inputTokens: 1, outputTokens: 1 } }; } expect(request.messages.at(-2)).toMatchObject({ role: 'assistant', toolCalls: [{ id: 'call-1', name: 'lookup', input: { q: 1 } }] }); expect(request.messages.at(-1)).toMatchObject({ role: 'tool', toolCallId: 'call-1' }); return { stop: 'complete', usage: { inputTokens: 1, outputTokens: 1 } }; } }; const tools = new ToolRegistry(); tools.register(definition(async () => { calls += 1; return { answer: 1 }; }), 'builtin'); const events: string[] = []; const kernel = new RuntimeKernel({ sessionId: sessionId('s'), model, tools, emit: async (event) => { events.push(event.type); } }); await kernel.submit('go'); expect(calls).toBe(1); expect(requests).toEqual([1, 3]); expect(events).toContain('tool.started'); expect(events).toContain('tool.ended'); expect(kernel.snapshot().usage).toEqual({ inputTokens: 2, outputTokens: 2 }); });
  it('records one ordered assistant tool-call envelope before multiple correlated results', async () => { const executed: string[] = []; let iteration = 0; const model: ModelPort = { run: async (request, context) => { iteration += 1; if (iteration === 1) { await context.emit?.({ type: 'text', text: 'checking' }); await context.emit?.({ type: 'tool-call', id: 'call-a', name: 'alpha', input: { order: 1 } }); await context.emit?.({ type: 'tool-call', id: 'call-b', name: 'beta', input: { order: 2 } }); return { stop: 'tool', usage: { inputTokens: 0, outputTokens: 0 } }; } expect(request.messages).toEqual([
      { role: 'user', content: 'go' },
      { role: 'assistant', content: 'checking', toolCalls: [{ id: 'call-a', name: 'alpha', input: { order: 1 } }, { id: 'call-b', name: 'beta', input: { order: 2 } }] },
      { role: 'tool', toolCallId: 'call-a', content: JSON.stringify({ ok: true, content: 'alpha', detailsVersion: 1 }) },
      { role: 'tool', toolCallId: 'call-b', content: JSON.stringify({ ok: true, content: 'beta', detailsVersion: 1 }) },
    ]); return { stop: 'complete', usage: { inputTokens: 0, outputTokens: 0 } }; } }; const tools = new ToolRegistry(); tools.register(definition(async () => { executed.push('alpha'); return 'alpha'; }, 'alpha'), 'builtin'); tools.register(definition(async () => { executed.push('beta'); return 'beta'; }, 'beta'), 'builtin'); await new RuntimeKernel({ sessionId: sessionId('s'), model, tools }).submit('go'); expect(executed).toEqual(['alpha', 'beta']); });
  it('does not execute a denied effect', async () => { let executed = false; let iteration = 0; const model: ModelPort = { run: async (_request, context) => { iteration += 1; if (iteration === 1) { await context.emit?.({ type: 'tool-call', id: 'call-denied', name: 'lookup', input: {} }); return { stop: 'tool', usage: { inputTokens: 0, outputTokens: 0 } }; } return { stop: 'complete', usage: { inputTokens: 0, outputTokens: 0 } }; } }; const tools = new ToolRegistry(); tools.register(definition(async () => { executed = true; }), 'builtin'); const policy = new PolicyChain(); policy.use('managed', async () => ({ effect: 'deny', reason: 'no', category: 'trust' })); const kernel = new RuntimeKernel({ sessionId: sessionId('s'), model, tools, policy }); await kernel.submit('go'); expect(executed).toBe(false); });
  it('fails closed at the iteration bound', async () => { let id = 0; const model: ModelPort = { run: async (_request, context) => { await context.emit?.({ type: 'tool-call', id: `missing-${++id}`, name: 'missing', input: {} }); return { stop: 'tool', usage: { inputTokens: 0, outputTokens: 0 } }; } }; const kernel = new RuntimeKernel({ sessionId: sessionId('s'), model, maxIterations: 2 }); await expect(kernel.submit('loop')).rejects.toMatchObject({ category: 'internal-invariant' }); expect(kernel.snapshot().state).toBe('failed'); });
});
