import { describe, expect, it } from 'vitest';
import { RuntimeFailure, TransactionalSessionStore, branchId, importLegacySession, revision, sessionEventId, sessionId, type SessionEvent, type SessionRecordPort } from '../src/index.js';
class RecordPort implements SessionRecordPort {
  content: string | null = null; backup: string | null = null; failCommit = false;
  async read(): Promise<{ content: string; recovered: boolean } | null> { if (this.content === null && this.backup === null) return null; const content = this.content ?? this.backup!; return { content, recovered: this.content === null }; }
  async commit(_id: unknown, expected: string, _next: string, content: string): Promise<void> { const current = this.content === null ? '0' : String((JSON.parse(this.content) as { events: unknown[] }).events.length); if (expected !== current) throw new RuntimeFailure('session-conflict', 'durable conflict', 'safe'); if (this.failCommit) throw new Error('interrupted before rename'); this.backup = this.content; this.content = content; }
}
const make = (sequence: number, event: SessionEvent['event']): SessionEvent => ({ schemaVersion: 1, sessionId: sessionId('s'), eventId: sessionEventId(`e${sequence}`), revision: revision(String(sequence)), sequence, timestamp: sequence, visibility: 'internal', event });
describe('transactional persistence and migration', () => {
  it('preserves the last commit across an interrupted write and rejects corruption', async () => { const port = new RecordPort(); const store = new TransactionalSessionStore(port); await store.append(sessionId('s'), revision('0'), [make(1, { type: 'session.created' })]); const committed = port.content; port.failCommit = true; await expect(store.append(sessionId('s'), revision('1'), [make(2, { type: 'session.renamed', name: 'two' })])).rejects.toMatchObject({ category: 'persistence' }); expect(port.content).toBe(committed); port.content = '{bad'; await expect(store.load(sessionId('s'))).rejects.toMatchObject({ category: 'session-corruption' }); });
  it('projects branches and preserves unknown legacy entries as opaque without mutating the source', async () => { const store = new TransactionalSessionStore(new RecordPort()); const records = [{ type: 'session', name: 'old' }, { type: 'branch', id: 'child', parentId: 'main' }, { type: 'future', payload: 1 }]; let digestCalls = 0; const receipt = await importLegacySession({ sourceId: 'pi-jsonl', digest: async () => { digestCalls += 1; return 'same'; }, readRecords: async function* () { yield* records; } }, store, sessionId('s'), () => 1); const loaded = await store.load(sessionId('s')); expect(receipt.opaque).toBe(1); expect(digestCalls).toBe(2); expect(loaded.projection.branches).toEqual([{ id: branchId('child'), parentId: branchId('main') }]); expect(loaded.events.some(({ event }) => event.type === 'opaque.imported')).toBe(true); });
});
