import {
  authority,
  thinkFirst,
  workMode,
  awareness,
  tools,
  searchAndResearch,
  octocodeCli,
  skills,
  code,
  testing,
  docs,
  output,
  context,
  agents,
  browserAgent,
  safety,
  ultimateReminders,
} from './sections/index.js';

/** The full Octocode system prompt — sections in the order they appear below. */
export const SYSTEM_PROMPT =
  [
    authority,
    safety,
    workMode,
    awareness,
    thinkFirst,
    octocodeCli,
    skills,
    agents,
    tools,
    browserAgent,
    searchAndResearch,
    code,
    testing,
    docs,
    context,
    output,
    ultimateReminders,
  ].join('\n\n') + '\n';
