import {
  chmodSync,
  closeSync,
  existsSync,
  fsyncSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { randomUUID } from 'node:crypto';
import { dirname, resolve } from 'node:path';

export const OPENCODE_AWARENESS_PLUGIN_FILE = 'octocode-awareness.js';
export const OPENCODE_AWARENESS_PLUGIN_MARKER = '// Generated by @octocodeai/octocode-awareness.';

export interface OpenCodeAwarenessPluginOptions {
  hookRunnerPath: string;
  skillRoot: string;
  nodePath?: string;
}

export interface OpenCodeAwarenessInstallOptions extends OpenCodeAwarenessPluginOptions {
  projectDir: string;
}

export interface OpenCodeAwarenessInstallResult {
  changed: boolean;
  pluginPath: string;
}

function requiredAbsolutePath(value: string, label: string): string {
  if (!value.trim()) throw new Error(`${label} is required`);
  return resolve(value);
}

function validateOpenCodeSources(options: OpenCodeAwarenessPluginOptions): void {
  const hookRunnerPath = requiredAbsolutePath(options.hookRunnerPath, 'hookRunnerPath');
  const skillRoot = requiredAbsolutePath(options.skillRoot, 'skillRoot');
  if (!existsSync(hookRunnerPath) || !statSync(hookRunnerPath).isFile()) {
    throw new Error(`hook runner does not exist: ${hookRunnerPath}`);
  }
  if (!existsSync(skillRoot) || !statSync(skillRoot).isDirectory()) {
    throw new Error(`skill root does not exist: ${skillRoot}`);
  }
}

/**
 * Generate a dependency-light OpenCode V2 plugin. The generated adapter owns only
 * host translation: all Awareness decisions and mutations remain in the one
 * bundled hook runner.
 */
export function generateOpenCodeAwarenessPlugin(options: OpenCodeAwarenessPluginOptions): string {
  const runner = requiredAbsolutePath(options.hookRunnerPath, 'hookRunnerPath');
  const skillRoot = requiredAbsolutePath(options.skillRoot, 'skillRoot');
  const nodePath = requiredAbsolutePath(options.nodePath ?? process.execPath, 'nodePath');

  return `${OPENCODE_AWARENESS_PLUGIN_MARKER} Do not add hook logic here.
import { spawn } from "node:child_process";
import { Plugin } from "@opencode-ai/plugin";

const runner = ${JSON.stringify(runner)};
const skillRoot = ${JSON.stringify(skillRoot)};
const nodePath = ${JSON.stringify(nodePath)};
const writeTools = new Set(["apply_patch", "delete", "edit", "multiedit", "patch", "write"]);

function record(value) {
  return value && typeof value === "object" ? value : {};
}

function sessionID(event) {
  const properties = record(event.properties);
  const info = record(properties.info);
  const session = record(event.session);
  return event.sessionID ?? event.sessionId ?? session.id ?? info.id;
}

function workspace(ctx, event) {
  const properties = record(event.properties);
  const info = record(properties.info);
  return event.cwd ?? info.directory ?? ctx.location?.project?.canonical ?? ctx.location?.directory ?? process.cwd();
}

function payload(ctx, event, hookEventName) {
  return {
    hook_event_name: hookEventName,
    cwd: workspace(ctx, event),
    session_id: sessionID(event),
    tool_name: event.tool,
    tool_use_id: event.callID ?? event.callId ?? event.id,
    tool_input: event.input,
    tool_response: event.status === "completed" ? event.result : event.output,
    is_error: event.status === "error",
    reason: event.type,
  };
}

function invoke(command, hookPayload, blocking = false) {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(nodePath, [runner, command, "--host", "opencode", "--skill-root", skillRoot], {
      env: { ...process.env, OCTOCODE_AGENT_HOST: "opencode" },
      stdio: ["pipe", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    let settled = false;
    const finish = (callback, value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      callback(value);
    };
    const timeout = setTimeout(() => {
      child.kill("SIGTERM");
      console.error(\`octocode-awareness OpenCode hook \${command} timed out\`);
      finish(resolvePromise, "");
    }, 20_000);
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (chunk) => { stdout += chunk; });
    child.stderr.on("data", (chunk) => { stderr += chunk; });
    child.on("error", (error) => {
      console.error("octocode-awareness OpenCode hook warning:", error);
      finish(resolvePromise, "");
    });
    child.on("close", (code) => {
      if (code === 0) {
        finish(resolvePromise, stdout);
        return;
      }
      const message = stderr.trim() || \`octocode-awareness hook \${command} exited \${code ?? "unknown"}\`;
      if (blocking && code === 2) finish(reject, new Error(message));
      else {
        console.error(message);
        finish(resolvePromise, stdout);
      }
    });
    child.stdin.end(JSON.stringify(hookPayload));
  });
}

export default Plugin.define({
  id: "octocode.awareness",
  async setup(ctx) {
    await ctx.tool.hook("execute.before", async (event) => {
      if (!writeTools.has(String(event.tool).toLowerCase())) return;
      await invoke("pre-edit", payload(ctx, event, "tool.execute.before"), true);
    });
    await ctx.tool.hook("execute.after", async (event) => {
      if (!writeTools.has(String(event.tool).toLowerCase())) return;
      await invoke("post-edit", payload(ctx, event, "tool.execute.after"));
    });

    const controller = new AbortController();
    void (async () => {
      for await (const event of ctx.event.subscribe({ signal: controller.signal })) {
        switch (event.type) {
          case "session.created":
            await invoke("notify-deliver", payload(ctx, event, event.type));
            break;
          case "session.compacted":
            await invoke("session-compact", payload(ctx, event, event.type));
            break;
          case "session.deleted":
            await invoke("session-end", payload(ctx, event, event.type));
            break;
          case "session.idle":
            await invoke("stop-verify", payload(ctx, event, event.type));
            break;
        }
      }
    })().catch((error) => {
      if (!controller.signal.aborted) console.error("octocode-awareness OpenCode event warning:", error);
    });
    return () => controller.abort();
  },
});
`;
}

export function openCodeAwarenessPluginPath(projectDir: string): string {
  return resolve(requiredAbsolutePath(projectDir, 'projectDir'), '.opencode', 'plugins', OPENCODE_AWARENESS_PLUGIN_FILE);
}

export function inspectOpenCodeAwarenessPlugin(options: OpenCodeAwarenessInstallOptions): {
  pluginPath: string;
  exists: boolean;
  owned: boolean;
  exact: boolean;
  source: string;
} {
  validateOpenCodeSources(options);
  const pluginPath = openCodeAwarenessPluginPath(options.projectDir);
  const source = generateOpenCodeAwarenessPlugin(options);
  if (!existsSync(pluginPath)) return { pluginPath, exists: false, owned: false, exact: false, source };
  if (lstatSync(pluginPath).isSymbolicLink()) {
    throw new Error(`OpenCode plugin path must not be a symbolic link: ${pluginPath}`);
  }
  const current = readFileSync(pluginPath, 'utf8');
  return {
    pluginPath,
    exists: true,
    owned: current.startsWith(OPENCODE_AWARENESS_PLUGIN_MARKER),
    exact: current === source,
    source,
  };
}

export function removeOpenCodeAwarenessPlugin(options: OpenCodeAwarenessInstallOptions): OpenCodeAwarenessInstallResult {
  const status = inspectOpenCodeAwarenessPlugin(options);
  if (!status.exists) return { changed: false, pluginPath: status.pluginPath };
  if (!status.owned) throw new Error(`refusing to remove unowned OpenCode plugin: ${status.pluginPath}`);
  unlinkSync(status.pluginPath);
  return { changed: true, pluginPath: status.pluginPath };
}

function writeAtomic(file: string, content: string): void {
  mkdirSync(dirname(file), { recursive: true });
  const temporary = `${file}.tmp-${process.pid}-${randomUUID()}`;
  const descriptor = openSync(temporary, 'wx', 0o600);
  try {
    writeFileSync(descriptor, content, 'utf8');
    fsyncSync(descriptor);
  } finally {
    closeSync(descriptor);
  }
  try {
    renameSync(temporary, file);
    chmodSync(file, 0o600);
  } finally {
    try { unlinkSync(temporary); } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
  }
}

/**
 * Install the plugin into OpenCode's auto-discovered project plugin directory.
 * No OpenCode JSON is rewritten, so unrelated configuration and JSONC comments
 * remain byte-for-byte intact.
 */
export function installOpenCodeAwarenessPlugin(options: OpenCodeAwarenessInstallOptions): OpenCodeAwarenessInstallResult {
  const projectDir = requiredAbsolutePath(options.projectDir, 'projectDir');
  validateOpenCodeSources(options);

  const pluginPath = openCodeAwarenessPluginPath(projectDir);
  if (existsSync(pluginPath) && lstatSync(pluginPath).isSymbolicLink()) {
    throw new Error(`OpenCode plugin path must not be a symbolic link: ${pluginPath}`);
  }
  const source = generateOpenCodeAwarenessPlugin({
    hookRunnerPath: options.hookRunnerPath,
    skillRoot: options.skillRoot,
    nodePath: options.nodePath,
  });
  if (existsSync(pluginPath) && readFileSync(pluginPath, 'utf8') === source) {
    return { changed: false, pluginPath };
  }
  writeAtomic(pluginPath, source);
  return { changed: true, pluginPath };
}
