import { AwarenessQueryRow } from './repo-model.js';
import { summarize } from './repo-formats.js';
import { rowFiles } from './repo-files.js';

export function renderDeveloperReviewDoc(rows: AwarenessQueryRow[], maxLines: number): string {
  const open = rows.filter(row => String(row['state']) !== 'done');
  const resolved = rows.filter(row => String(row['state']) === 'done');
  const lines = [
    '# Developer Review',
    '',
    '<!-- Generated by `npx @octocodeai/octocode-awareness reflect developer-review --format markdown`. -->',
    '',
    'Feedback from awareness_agents to the human who authors this repo\'s agent instructions',
    '(root `AGENTS.md`, `.octocode/AGENTS.md`, SKILL.md, system prompt, task briefs).',
    'Each item is where the *instructions* — not the code, not the harness — were ambiguous,',
    'wrong, over-constraining, or missing context. Recorded via `reflect record --fix-instructions`.',
    '',
    `Open: ${open.length} · Resolved: ${resolved.length}`,
    '',
  ];

  if (rows.length === 0) {
    lines.push(
      'No instruction feedback yet.',
      '',
      'Agents: when your instructions cost you time or a wrong turn, record it:',
      '`npx @octocodeai/octocode-awareness reflect record --outcome partial --task "<what you did>" \\',
      '  --fix-instructions "<what the instructions should have said>"`',
      '',
    );
    return lines.join('\n');
  }

  function renderSection(title: string, sectionRows: AwarenessQueryRow[]): void {
    if (sectionRows.length === 0) return;
    lines.push(`## ${title} (${sectionRows.length})`, '');
    for (const row of sectionRows) {
      const source = String(row['source']);
      const state = String(row['state']);
      const agent = String(row['agent_id'] ?? 'agent');
      const files = rowFiles(row);
      const block = [`- ${summarize(String(row['feedback']), 240)}`];
      const meta = [`from ${agent}`, `via ${source}${state && state !== 'recorded' ? `:${state}` : ''}`, `id \`${row['id']}\``];
      if (files.length > 0) meta.push(`files: ${files.slice(0, 3).join(', ')}${files.length > 3 ? ` +${files.length - 3}` : ''}`);
      block.push(`  - ${meta.join(' · ')}`);
      if (maxLines && lines.length + block.length + 1 > maxLines) {
        lines.push(`- …more omitted by projection cap. Use \`query developer-review\` or \`reflect developer-review\`.`, '');
        return;
      }
      lines.push(...block);
    }
    lines.push('');
  }

  renderSection('Open', open);
  renderSection('Resolved', resolved);
  return lines.join('\n');
}
