#!/usr/bin/env node
/**
 * @octocodeai/octocode-awareness build script.
 *
 * Builds directly to out/ (no atomic staging).
 * Shared esbuild config from repo-root build.config.mjs.
 * Run `yarn typecheck` for a type-only check without rebuilding.
 */
import * as esbuild from 'esbuild';
import { execFileSync } from 'node:child_process';
import {
  chmodSync, cpSync, existsSync, mkdirSync,
  readFileSync, readdirSync, rmSync, writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { baseOptions } from '../../build.config.mjs';
import { coreEntryPoints, liteEntryPoints, skillScriptEntries } from './build.entries.mjs';

const packageRoot = dirname(fileURLToPath(import.meta.url));
const repoRoot    = resolve(packageRoot, '../..');
const outDir      = join(packageRoot, 'out');
const skillScriptsOutDir = join(outDir, 'skill-scripts');

// Canonical repo-root skill source (synced to package-local at build time).
const canonicalSkillsRoot       = join(repoRoot, 'skills');
const packageSkillsRoot         = join(packageRoot, 'skills');
const canonicalAwarenessScripts = join(canonicalSkillsRoot, 'octocode-awareness', 'scripts');
const agentSkillsRoot           = join(repoRoot, '.agents', 'skills');

const tscBin  = resolve(packageRoot, '../../node_modules/.bin/tsc');
const require = createRequire(import.meta.url);

// ── Skill helpers ─────────────────────────────────────────────────────────────

function hasSkillDirectories(root) {
  if (!existsSync(root)) return false;
  return readdirSync(root, { withFileTypes: true })
    .some((e) => e.isDirectory() && existsSync(join(root, e.name, 'SKILL.md')));
}

function resolveSkillSourceRoot() {
  if (hasSkillDirectories(canonicalSkillsRoot)) return canonicalSkillsRoot;
  if (hasSkillDirectories(packageSkillsRoot))   return packageSkillsRoot;
  try {
    const p = join(dirname(require.resolve('octocode/package.json')), 'skills');
    if (hasSkillDirectories(p)) return p;
  } catch { /* fall through */ }
  return canonicalSkillsRoot;
}

// ── Shebang + chmod helpers ───────────────────────────────────────────────────

const warningGuard = [
  '#!/usr/bin/env node',
  "process.removeAllListeners('warning');",
  "process.on('warning', (w) => {",
  "  if (w?.name === 'ExperimentalWarning' && String(w?.message).includes('SQLite')) return;",
  '  console.error(w?.stack ?? String(w));',
  '});',
].join('\n');

const generatedNote =
  '// @generated by packages/octocode-awareness/build.mjs — do not edit; run `yarn build` to refresh.';

function makeExecutable(filePath, banner = '#!/usr/bin/env node') {
  const src = readFileSync(filePath, 'utf8');
  writeFileSync(filePath, `${banner}\n${src.replace(/^#![^\n]*\n?/, '')}`);
  chmodSync(filePath, 0o755);
}

// ── Clean ─────────────────────────────────────────────────────────────────────

process.chdir(packageRoot);
rmSync(outDir, { recursive: true, force: true });
rmSync(join(packageRoot, 'dist'), { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

// ── Core bundle (code-split) ──────────────────────────────────────────────────

await esbuild.build({
  ...baseOptions,
  entryPoints:  coreEntryPoints,
  outdir:       outDir,
  entryNames:   '[name]',
  chunkNames:   'chunks/[name]-[hash]',
  splitting:    true,
  minify:       true,
});

// ── Skill-script standalone bundles (no shared chunks) ────────────────────────

mkdirSync(skillScriptsOutDir, { recursive: true });
await Promise.all(
  skillScriptEntries.map(({ entryPoints, outfileName }) =>
    esbuild.build({
      ...baseOptions,
      entryPoints,
      outfile: join(skillScriptsOutDir, outfileName),
      minify:  true,
    }),
  ),
);

// ── Awareness Lite (self-contained, no shared chunks) ─────────────────────────

await esbuild.build({
  ...baseOptions,
  entryPoints: liteEntryPoints,
  outdir:      join(outDir, 'lite'),
  entryNames:  '[name]',
  splitting:   false,
  minify:      true,
});

// ── Type declarations (tsc --emitDeclarationOnly → out/types/) ────────────────

execFileSync(
  tscBin,
  ['--emitDeclarationOnly', '--outDir', join(outDir, 'types'), '-p', 'tsconfig.build.json'],
  { cwd: packageRoot, stdio: 'inherit' },
);

// ── Shebangs + chmod ──────────────────────────────────────────────────────────

for (const name of ['octocode-awareness.js', 'hook-runner.js']) {
  makeExecutable(join(outDir, name), warningGuard);
}
makeExecutable(join(outDir, 'lite', 'cli.js'), warningGuard);
for (const name of ['extract-hook-files.js']) {
  makeExecutable(join(outDir, name));
}
for (const name of ['awareness.mjs', 'hook-runner.mjs']) {
  makeExecutable(join(skillScriptsOutDir, name), `${warningGuard}\n${generatedNote}`);
}
makeExecutable(join(skillScriptsOutDir, 'extract-hook-files.mjs'), `#!/usr/bin/env node\n${generatedNote}`);

// ── Static assets ─────────────────────────────────────────────────────────────

cpSync(join(packageRoot, 'docs'),   join(outDir, 'docs'),   { recursive: true });
cpSync(join(packageRoot, 'assets'), join(outDir, 'assets'), { recursive: true });

// ── Skills ────────────────────────────────────────────────────────────────────

const skillSourceRoot  = resolveSkillSourceRoot();
const usingCanonical   = skillSourceRoot === canonicalSkillsRoot;
const retiredSkills    = new Set(['octocode-agent-communication', 'octocode-reflection']);
const shouldCopyFile   = (_src, p) =>
  !p.split(/[\\/]/).includes('node_modules') && !p.endsWith('octocode-config.mjs');

if (!existsSync(skillSourceRoot)) {
  throw new Error(`Missing skill source root: ${skillSourceRoot}`);
}

const bundledSkills = readdirSync(skillSourceRoot, { withFileTypes: true })
  .filter((e) => e.isDirectory() && !retiredSkills.has(e.name) && existsSync(join(skillSourceRoot, e.name, 'SKILL.md')))
  .map((e) => e.name)
  .sort();

if (bundledSkills.length === 0) {
  throw new Error(`No bundled skills found in ${skillSourceRoot}`);
}

const packagedSkillsRoot = join(outDir, 'skills');
rmSync(packagedSkillsRoot, { recursive: true, force: true });
mkdirSync(packagedSkillsRoot, { recursive: true });

if (usingCanonical) {
  mkdirSync(agentSkillsRoot, { recursive: true });
  for (const s of retiredSkills) {
    rmSync(join(agentSkillsRoot, s), { recursive: true, force: true });
  }
}

for (const skillName of bundledSkills) {
  const source = join(skillSourceRoot, skillName);
  const filter = (p) => shouldCopyFile(source, p);

  cpSync(source, join(packagedSkillsRoot, skillName), { recursive: true, filter });

  if (usingCanonical) {
    const mirrored = join(agentSkillsRoot, skillName);
    rmSync(mirrored, { recursive: true, force: true });
    cpSync(source, mirrored, { recursive: true, filter });

    // Keep package-local skills/ in sync for npm consumers / subset checkouts.
    const pkgCopy = join(packageSkillsRoot, skillName);
    rmSync(pkgCopy, { recursive: true, force: true });
    cpSync(source, pkgCopy, { recursive: true, filter });
  }
}

// Inject generated scripts into the canonical Awareness skill (repo-root source).
if (usingCanonical) {
  mkdirSync(canonicalAwarenessScripts, { recursive: true });
  for (const name of ['awareness.mjs', 'hook-runner.mjs', 'extract-hook-files.mjs']) {
    cpSync(join(skillScriptsOutDir, name), join(canonicalAwarenessScripts, name));
  }
  // Remove stale generated artefacts from older builds.
  for (const stale of ['runtime', 'schemas']) {
    rmSync(join(canonicalAwarenessScripts, stale), { recursive: true, force: true });
  }
  rmSync(join(canonicalAwarenessScripts, 'schema.mjs'), { force: true });
}

// Inject scripts into the packaged copy of the Awareness skill.
const packagedAwarenessScripts = join(packagedSkillsRoot, 'octocode-awareness', 'scripts');
if (existsSync(packagedAwarenessScripts)) {
  for (const name of ['awareness.mjs', 'hook-runner.mjs', 'extract-hook-files.mjs']) {
    cpSync(join(skillScriptsOutDir, name), join(packagedAwarenessScripts, name));
  }
  rmSync(join(packagedAwarenessScripts, 'schemas'), { recursive: true, force: true });
  rmSync(join(packagedAwarenessScripts, 'schema.mjs'), { force: true });
}

// ── Summary ───────────────────────────────────────────────────────────────────

const chunkCount = readdirSync(join(outDir, 'chunks')).length;
console.log('✓ @octocodeai/octocode-awareness built → out/');
console.log(`✓ Awareness CLI → out/octocode-awareness.js (${chunkCount} shared chunks)`);
console.log('✓ schemas served dynamically by the CLI (no static schema files)');
console.log(`✓ bundled skills → out/skills/ (${bundledSkills.join(', ')}) from ${skillSourceRoot}`);
